"""Tests for scripts/ci_lock_subset.py.

The script exists so CI can install the SHIPPED versions (the lock) rather than
the loose pins, minus the two native-window packages a bare ubuntu runner
cannot take. Its whole value is that it fails loudly instead of quietly
degrading, so most of what is worth testing here is the failure paths.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "ci_lock_subset.py"
REAL_LOCK = ROOT / "requirements-lock.txt"


def _load():
    spec = importlib.util.spec_from_file_location("ci_lock_subset", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["ci_lock_subset"] = mod
    spec.loader.exec_module(mod)
    return mod


mod = _load()


# Mirrors the real shape this is used on: "webview" is top-level (pywebview),
# "netbridge" is top-level AND required by webview (pythonnet), "shared" is a
# pure transitive of netbridge (clr-loader).
#
# Note the direction of "# via": it names the packages that require THIS one.
# So "shared  # via netbridge" means netbridge depends on shared.
SYNTHETIC = """\
# generated by pip-compile
netbridge==2.0 \\
    --hash=sha256:ccc
    # via
    #   -r requirements.txt
    #   webview
shared==3.0 \\
    --hash=sha256:ddd
    # via netbridge
webview==1.0 \\
    --hash=sha256:aaa \\
    --hash=sha256:bbb
    # via -r requirements.txt
"""


def test_drops_the_whole_block_not_just_the_pin_line():
    """The bug a naive grep -v would introduce: orphaned --hash lines.

    Those do not vanish -- pip reads them as continuations of the PREVIOUS
    package, silently attaching one package's hashes to another.
    """
    out = mod.build_subset(SYNTHETIC, ["webview", "netbridge"])
    assert "webview==1.0" not in out
    assert "sha256:aaa" not in out and "sha256:bbb" not in out
    assert "netbridge==2.0" not in out and "sha256:ccc" not in out
    # The transitive survives intact -- installing it is harmless.
    assert "shared==3.0" in out and "sha256:ddd" in out


def test_preamble_is_preserved():
    out = mod.build_subset(SYNTHETIC, ["webview", "netbridge"])
    assert out.startswith("# generated by pip-compile")


def test_dropping_a_package_a_kept_one_requires_is_refused():
    """webview requires netbridge, so netbridge cannot go alone."""
    with pytest.raises(SystemExit) as exc:
        mod.build_subset(SYNTHETIC, ["netbridge"])
    msg = str(exc.value)
    assert "cannot drop 'netbridge'" in msg
    assert "webview" in msg


def test_dropping_a_pure_transitive_is_refused():
    with pytest.raises(SystemExit) as exc:
        mod.build_subset(SYNTHETIC, ["shared"])
    assert "netbridge" in str(exc.value)


def test_top_level_via_is_not_treated_as_a_dependant():
    """'# via -r requirements.txt' is a pin source, not a package."""
    out = mod.build_subset(SYNTHETIC, ["webview"])
    assert "webview==" not in out
    assert "netbridge==2.0" in out


def test_absent_exclude_name_is_an_error_not_a_silent_no_op():
    """A rename upstream must not turn the filter into a no-op."""
    with pytest.raises(SystemExit) as exc:
        mod.build_subset(SYNTHETIC, ["webview", "nosuchpkg"])
    assert "nosuchpkg" in str(exc.value)


def test_name_normalisation_is_pep503():
    assert mod.canon("Clr_Loader") == mod.canon("clr-loader") == "clr-loader"
    out = mod.build_subset(SYNTHETIC, ["WebView"])
    assert "webview==" not in out


def test_not_a_lock_file_is_an_error():
    with pytest.raises(SystemExit):
        mod.build_subset("# just a comment\n", ["alpha"])


# --- against the real lock -------------------------------------------------

def test_real_lock_drops_exactly_the_native_pair():
    """The exclusion CI actually applies must stay valid as the lock evolves.

    If pywebview or pythonnet is renamed or gains a dependant, this fails here
    rather than 20 minutes later inside a CI install step.
    """
    text = REAL_LOCK.read_text(encoding="utf-8")
    out = mod.build_subset(text, ["pywebview", "pythonnet"])

    import re
    pins = lambda s: {mod.canon(m.group(1))
                      for m in re.finditer(r"(?m)^([A-Za-z0-9][A-Za-z0-9._-]*)==", s)}

    before, after = pins(text), pins(out)
    assert before - after == {"pywebview", "pythonnet"}
    assert after  # not empty


def test_real_lock_subset_keeps_every_hash_block_well_formed():
    """Every pin line must still be followed by at least one hash."""
    out = mod.build_subset(REAL_LOCK.read_text(encoding="utf-8"),
                           ["pywebview", "pythonnet"])
    lines = out.splitlines()
    pin_idx = [i for i, ln in enumerate(lines) if mod._PIN_RE.match(ln)]
    for i in pin_idx:
        assert lines[i].rstrip().endswith("\\"), lines[i]
        assert "--hash=sha256:" in lines[i + 1], lines[i]

    # And no hash line may be left stranded above the first pin.
    first = pin_idx[0]
    assert not any("--hash=" in ln for ln in lines[:first])
