#!/usr/bin/env python3
"""
HDFC Bank statement → canonical 8-column CSV.

Supports two input formats:
  PDF (scanned image):
    1. Rasterize each page with pypdfium2 at 2.5x (≈225 DPI)
    2. OCR with pytesseract (--psm 6)
    3. Regex-parse transaction lines

  XLS/XLSX (net-banking download):
    1. Read with xlrd (.xls) or openpyxl (.xlsx) — pure Python, no external tools
    2. Auto-detect header row (looks for 'Date' + 'Narration')
    3. Deterministic column mapping

Canonical output columns:
  Date, Transaction ID, Description, Account, Deposit, Withdrawal, Balance, Currency

Requires:
  PDF path:  pypdfium2, pytesseract, tesseract binary
  XLS path:  xlrd  (pip install xlrd)
  XLSX path: openpyxl (pip install openpyxl)
"""
import csv
import logging
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from agents.balance_utils import (
    verify_running_balance,
    verify_closing_balance,
    format_balance_summary,
)

log = logging.getLogger(__name__)


CANONICAL_COLS = [
    "Date", "Transaction ID", "Description", "Account",
    "Deposit", "Withdrawal", "Balance", "Currency",
]

# ── Helpers ──────────────────────────────────────────────────────────────────

def _clean_amount(s: str) -> str:
    """Strip commas; return '' for zero."""
    s = str(s).replace(',', '').strip()
    try:
        return '' if float(s) == 0.0 else s
    except ValueError:
        return s


def _normalise_date(d: str) -> str:
    """Normalise HDFC dates to ISO YYYY-MM-DD.

    Input formats:
        DD/MM/YY   (8 chars, PDF OCR)
        DD/MM/YYYY (10 chars, XLS export)
    """
    parts = d.strip().split('/')
    if len(parts) != 3:
        return d  # unexpected — return as-is
    dd, mm, yy = parts[0], parts[1], parts[2]
    if len(yy) == 2:
        yy = f"20{yy}"
    return f"{yy}-{mm}-{dd}"


# ── PDF path ─────────────────────────────────────────────────────────────────

_DATE_RE = re.compile(r'^(\d{2}/\d{2}/\d{2})\s*\|')
_TAIL_RE = re.compile(
    r'(\d{15})\s*\|\s*'
    r'(\d{2}/\d{2}/\d{2})\s+'
    r'([\d,]+\.?\d*)\s+'
    r'([\d,]+\.?\d*)\s+'
    r'([\d,]+\.?\d*)\s*$'
)


def _ocr_pdf(pdf_path: str) -> str:
    import pypdfium2 as pdfium
    import pytesseract
    pdf = pdfium.PdfDocument(pdf_path)
    pages_text = []
    for i in range(len(pdf)):
        page = pdf[i]
        bitmap = page.render(scale=2.5)
        pil_img = bitmap.to_pil()
        text = pytesseract.image_to_string(pil_img, config='--psm 6')
        pages_text.append(text)
    return '\n'.join(pages_text)


def _parse_pdf_transactions(ocr_text: str) -> list:
    lines = ocr_text.splitlines()

    start_idx = 0
    for i, line in enumerate(lines):
        if 'statement of account' in line.lower():
            start_idx = i + 1
            break

    transactions = []
    current = None
    current_text = ''

    for line in lines[start_idx:]:
        line = line.strip()
        if not line:
            continue

        low = line.lower()
        if any(k in low for k in [
            'closing balance', 'opening balance', 'total deposits',
            'total withdrawals', 'page no', 'statement of account',
            'generated on', 'generated by',
        ]):
            current = None
            current_text = ''
            continue

        m_date = _DATE_RE.match(line)
        if m_date:
            if current and current_text:
                m_tail = _TAIL_RE.search(current_text)
                if m_tail:
                    transactions.append(_build_pdf_txn(current, current_text, m_tail))
            current = {'date': m_date.group(1)}
            current_text = line
        elif current is not None:
            current_text += ' ' + line

        if current and current_text:
            m_tail = _TAIL_RE.search(current_text)
            if m_tail:
                transactions.append(_build_pdf_txn(current, current_text, m_tail))
                current = None
                current_text = ''

    if current and current_text:
        m_tail = _TAIL_RE.search(current_text)
        if m_tail:
            transactions.append(_build_pdf_txn(current, current_text, m_tail))

    return transactions


def _clean_ocr_desc(desc: str) -> str:
    """Remove common OCR artifacts from HDFC scanned-statement descriptions."""
    # Strip trailing pipe + special chars (column-separator noise)
    desc = re.sub(r'[\|]+\s*[—–_\-\s]*$', '', desc)
    # Strip trailing ' 0' (adjacent zero-column bleed)
    desc = re.sub(r'\s+0$', '', desc)
    # Strip embedded balance fragments like "0.00 3,443.00 46,988.00"
    desc = re.sub(r'\s+\d[\d,]*\.\d{2}\s+\d[\d,]*\.\d{2}\s+\d[\d,]*\.\d{2}', '', desc)
    # Collapse runs of pipes/spaces
    desc = re.sub(r'\s*\|\s*', ' ', desc)
    # Final cleanup
    return re.sub(r'\s+', ' ', desc).strip(' -|')


def _build_pdf_txn(current: dict, text: str, m_tail) -> dict:
    ref_no = m_tail.group(1)
    withdrawal = _clean_amount(m_tail.group(3))
    deposit    = _clean_amount(m_tail.group(4))
    balance    = m_tail.group(5).replace(',', '')

    pipe_idx = text.index('|') + 1
    ref_idx  = text.rfind(ref_no)
    raw_desc = text[pipe_idx:ref_idx].strip() if ref_idx > pipe_idx else ''
    desc = re.sub(r'\s+', ' ', raw_desc).strip(' -')
    desc = _clean_ocr_desc(desc)

    return {
        'Date': _normalise_date(current['date']),
        'Transaction ID': ref_no,
        'Description': desc,
        'Account': '',
        'Deposit': deposit,
        'Withdrawal': withdrawal,
        'Balance': balance,
        'Currency': 'INR',
    }


# ── XLS/XLSX path ─────────────────────────────────────────────────────────────

# HDFC XLS header columns (net-banking download format)
_HDFC_XLS_COLS = {
    'date':        ['date'],
    'value_date':  ['value dt', 'value date', 'val date', 'val dt'],
    'narration':   ['narration', 'description', 'particulars'],
    'nature':      ['nature of exp', 'nature', 'remarks'],
    'ref':         ['chq./ref.no.', 'chq/ref no', 'ref no', 'cheque no', 'reference no'],
    'withdrawal':  ['withdrawal amt.', 'withdrawal', 'debit', 'debit amt.'],
    'deposit':     ['deposit amt.', 'deposit', 'credit', 'credit amt.'],
    'balance':     ['closing balance', 'balance'],
}


def _read_xls_rows(file_path: str) -> list:
    """
    Read .xls or .xlsx into list of lists of strings.
    Uses xlrd for .xls, openpyxl for .xlsx.
    No LibreOffice required.
    """
    p = Path(file_path)
    suffix = p.suffix.lower()

    if suffix == '.xlsx':
        import openpyxl
        wb = openpyxl.load_workbook(str(p), data_only=True)
        ws = wb.active
        rows = []
        for row in ws.iter_rows(values_only=True):
            rows.append([str(c).strip() if c is not None else '' for c in row])
        return rows

    else:  # .xls (BIFF)
        try:
            import xlrd
        except ImportError:
            raise ImportError(
                "xlrd is required to read .xls files. "
                "Run: pip install xlrd"
            )
        wb = xlrd.open_workbook(str(p))
        ws = wb.sheet_by_index(0)
        rows = []
        for r in range(ws.nrows):
            row = []
            for c in range(ws.ncols):
                cell = ws.cell(r, c)
                if cell.ctype == xlrd.XL_CELL_DATE:
                    dt = xlrd.xldate_as_datetime(cell.value, wb.datemode)
                    row.append(dt.strftime('%d/%m/%Y'))
                elif cell.ctype == xlrd.XL_CELL_NUMBER:
                    v = cell.value
                    row.append(str(int(v)) if v == int(v) else str(v))
                elif cell.ctype == xlrd.XL_CELL_EMPTY:
                    row.append('')
                else:
                    row.append(str(cell.value).strip())
            rows.append(row)
        return rows


def _find_header_row(rows: list) -> int:
    """
    Find the row index whose first cell is 'Date' and second is 'Narration'
    (or similar). Returns -1 if not found.
    """
    for i, row in enumerate(rows):
        if len(row) >= 2:
            c0 = str(row[0]).strip().lower()
            c1 = str(row[1]).strip().lower()
            if c0 == 'date' and any(k in c1 for k in ['narration', 'description', 'particulars']):
                return i
    return -1


def _map_columns(header_row: list) -> dict:
    """
    Map canonical field names to column indices using the header row.
    Returns dict: field → col_index (or None if not found).
    """
    headers = [str(h).strip().lower() for h in header_row]
    result = {}
    for field, candidates in _HDFC_XLS_COLS.items():
        idx = None
        for h_idx, h in enumerate(headers):
            if any(c in h for c in candidates):
                idx = h_idx
                break
        result[field] = idx
    return result


def _parse_xls_transactions(rows: list) -> list:
    """Parse HDFC XLS rows into canonical transaction dicts."""
    header_idx = _find_header_row(rows)
    if header_idx == -1:
        raise ValueError(
            "Could not find HDFC header row (expected 'Date' + 'Narration'). "
            "Is this an HDFC net-banking XLS?"
        )

    col = _map_columns(rows[header_idx])

    # Validate required columns
    for required in ('date', 'narration', 'ref', 'withdrawal', 'deposit', 'balance'):
        if col.get(required) is None:
            raise ValueError(f"Required column '{required}' not found in header: {rows[header_idx]}")

    # Prefer Value Date over transaction Date when available
    date_col = col['value_date'] if col.get('value_date') is not None else col['date']

    transactions = []
    for row in rows[header_idx + 1:]:
        # Stop at empty rows or summary rows
        if not row or not str(row[0]).strip():
            continue
        date_raw = str(row[date_col]).strip()
        if not re.match(r'^\d{2}/\d{2}/\d{2,4}$', date_raw):
            continue  # Not a data row (totals, blank, etc.)

        narration = str(row[col['narration']]).strip() if col['narration'] is not None else ''
        nature    = str(row[col['nature']]).strip()    if col.get('nature') is not None else ''
        ref       = str(row[col['ref']]).strip()       if col['ref'] is not None else ''
        wdl       = _clean_amount(row[col['withdrawal']])  if col['withdrawal'] is not None else ''
        dep       = _clean_amount(row[col['deposit']])     if col['deposit'] is not None else ''
        bal       = _clean_amount(row[col['balance']])     if col['balance'] is not None else ''

        # Combine narration + nature of expense into description
        if nature and nature.lower() not in ('', 'none', 'nan'):
            desc = f"{narration} — {nature}"
        else:
            desc = narration

        # Strip leading zeros from ref (keep meaningful part)
        ref_clean = ref.lstrip('0') or ref  # preserve '0' if all zeros

        transactions.append({
            'Date': _normalise_date(date_raw),
            'Transaction ID': ref_clean,
            'Description': desc,
            'Account': '',
            'Deposit': dep,
            'Withdrawal': wdl,
            'Balance': bal,
            'Currency': 'INR',
        })

    return transactions


# ── Entry point ───────────────────────────────────────────────────────────────

def run(
    pdf_path: str,          # kept as param name for pipeline compat; accepts any path
    output_path: str,
    config_path: str = None,
    model_override: str = None,
) -> str:
    """
    Entry point: HDFC statement (PDF or XLS/XLSX) → canonical CSV.

    Args:
        pdf_path:       Path to HDFC statement (PDF, XLS, or XLSX).
        output_path:    Destination canonical CSV path.
        config_path:    Unused (no LLM needed).
        model_override: Unused.
    """
    input_path = str(pdf_path)
    if not Path(input_path).is_file():
        return f"❌ File not found: {input_path}"

    suffix = Path(input_path).suffix.lower()

    try:
        if suffix == '.pdf':
            ocr_text = _ocr_pdf(input_path)
            transactions = _parse_pdf_transactions(ocr_text)
            fmt = 'PDF (OCR)'
        elif suffix in ('.xls', '.xlsx'):
            rows = _read_xls_rows(input_path)
            transactions = _parse_xls_transactions(rows)
            fmt = suffix.upper()
        else:
            return (
                f"❌ Unsupported file type: {suffix}\n"
                "Supported: .pdf, .xls, .xlsx"
            )
    except Exception as e:
        return f"❌ Error processing {Path(input_path).name}: {e}"

    if not transactions:
        return (
            f"❌ No transactions found in {fmt} file.\n\n"
            "Possible causes: unexpected format, or this is not an HDFC statement."
        )

    # ── Balance verification ──────────────────────────────────────────────
    running = verify_running_balance(transactions)
    # Use the last transaction's balance as the expected closing balance
    # (source statement's closing balance = last row's balance)
    closing = verify_closing_balance(
        transactions,
        expected_closing=running["closing_balance"],
    )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=CANONICAL_COLS)
        writer.writeheader()
        writer.writerows(transactions)

    balance_info = format_balance_summary(running, closing)
    return (
        f"✓ HDFC ({fmt}): extracted {len(transactions)} transactions from "
        f"{Path(input_path).name} → canonical CSV\n"
        f"{balance_info}"
    )
