#!/usr/bin/env python3
"""
scripts/gen_docs.py — regenerate all help documentation from skill manifests.

Single source of truth = the `help:` block in each src/agents/*/skill.yaml
(plus the manifest fields the registry already parses: input file_types,
output suffix/extension, requires.native_binaries / .llm).

Renders, from that one source:
  * docs/user-guide/<skill_dir>.md   — one end-user guide per UI skill
  * docs/USER-GUIDE.html             — one self-contained, bundleable HTML guide
  * docs/dev/skills-reference.md      — developer reference (UI + 6 internal steps)

Usage:
    python scripts/gen_docs.py            # write all outputs
    python scripts/gen_docs.py --check    # exit 1 if anything would change (CI)

Editing help text: edit the skill's skill.yaml `help:` block and re-run this.
See docs/dev/help-block-schema.md and docs/dev/editing-help.md.
"""
from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

import yaml

# --- Locate project + make `agents` importable (mirrors the app's path setup).
ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
AGENTS = SRC / "agents"
DOCS = ROOT / "docs"
sys.path.insert(0, str(SRC))

from agents import registry  # noqa: E402  (after sys.path tweak)

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/gen_docs.py from skill.yaml help: blocks. "
    "Do not edit by hand — edit the manifest and re-run. -->"
)
MD_BANNER = (
    "<!-- GENERATED by scripts/gen_docs.py — do not edit by hand. "
    "Edit the skill's skill.yaml `help:` block and re-run `python scripts/gen_docs.py`. -->"
)


# ---------------------------------------------------------------------------
# Extract a uniform view per skill from manifest + help block.
# ---------------------------------------------------------------------------

def _output_pattern(skill: registry.SkillInfo) -> str:
    folder = (skill.help.output_folder if skill.help else "Data/outputs/").rstrip("/")
    if skill.output.type == "directory":
        return f"{folder}/YYYY-MM-DD-HHMMSS-{skill.output.suffix}/"
    return f"{folder}/YYYY-MM-DD-HHMMSS-<input>-{skill.output.suffix}{skill.output.extension}"


def _runs_offline(skill: registry.SkillInfo) -> bool:
    return not skill.requires.llm


def skill_view(skill: registry.SkillInfo) -> dict:
    """Flatten a SkillInfo + help block into a render-ready dict."""
    h = skill.help
    help_inputs = {hi.name: hi for hi in (h.inputs if h else ())}

    inputs = []
    for inp in skill.inputs:
        hi = help_inputs.get(inp.name)
        formats = ", ".join(inp.file_types) if inp.file_types else (
            "Text" if inp.type in ("text", "select") else "File / folder"
        )
        inputs.append({
            "label": inp.label,
            "required": inp.required,
            "formats": (hi.accepts if hi and hi.accepts else formats),
            "tooltip": hi.tooltip if hi else "",
            "gotchas": hi.gotchas if hi else "",
        })

    return {
        "name": skill.name,
        "display_name": skill.display_name,
        "dir": skill.manifest_path.parent.name,
        "category": skill.category,
        "mode": skill.mode,
        "offline": _runs_offline(skill),
        "native": list(skill.requires.native_binaries),
        "external": list(skill.requires.external_tools),
        "description": " ".join(skill.description.split()),
        "overview": (h.overview if h else ""),
        "when_to_use": (h.when_to_use if h else ""),
        "inputs": inputs,
        "steps": list(h.steps) if h else [],
        "output_folder": (h.output_folder if h else "Data/outputs/"),
        "output_pattern": _output_pattern(skill),
        "output_files": [{"name": f.name, "tooltip": f.tooltip}
                         for f in (h.output_files if h else ())],
        "tips": (h.tips if h else ""),
        "troubleshooting": [{"problem": t.problem, "fix": t.fix}
                            for t in (h.troubleshooting if h else ())],
        "has_help": bool(h and not h.is_empty()),
    }


def internal_steps() -> list[dict]:
    """Scan manifests the registry skips (no display_name) = internal steps."""
    steps = []
    ui_dirs = {s.manifest_path.parent.name for s in registry.discover()}
    for manifest in sorted(AGENTS.glob("*/skill.yaml")):
        if manifest.parent.name in ui_dirs:
            continue
        raw = yaml.safe_load(manifest.read_text(encoding="utf-8")) or {}
        if not isinstance(raw, dict) or "display_name" in raw:
            continue
        req = raw.get("requires") or {}
        steps.append({
            "dir": manifest.parent.name,
            "category": raw.get("category", "general"),
            "version": raw.get("version", "0.0.0"),
            "description": " ".join((raw.get("description") or "").split()),
            "llm": bool(req.get("llm", False)),
        })
    return steps


# ---------------------------------------------------------------------------
# Markdown rendering (per-skill end-user guide).
# ---------------------------------------------------------------------------

def render_skill_md(v: dict) -> str:
    badge = "🔌 offline (no LLM)" if v["offline"] else "🤖 needs an LLM endpoint"
    deps = ""
    if v["native"] or v["external"]:
        alldeps = ", ".join(v["native"] + v["external"])
        deps = f" · requires: {alldeps}"
    lines = [
        MD_BANNER,
        f"# {v['display_name']} — Usage Guide",
        "",
        f"*Mode: {v['mode']} · {badge}{deps}*",
        "",
        v["overview"] or v["description"],
        "",
    ]
    if v["when_to_use"]:
        lines += ["## When to use it", "", v["when_to_use"], ""]
    lines += ["## Inputs", ""]
    for inp in v["inputs"]:
        req = "required" if inp["required"] else "optional"
        lines.append(f"- **{inp['label']}** ({req}) — accepts: {inp['formats']}")
        if inp["tooltip"]:
            lines.append(f"  - {inp['tooltip']}")
        if inp["gotchas"]:
            lines.append(f"  - ⚠️ {inp['gotchas']}")
    lines += ["", "## How to run", ""]
    if v["steps"]:
        for i, s in enumerate(v["steps"], 1):
            lines.append(f"{i}. {s}")
    else:
        lines.append("1. Provide the input(s) above and click **Run**.")
    lines += [
        "",
        "## Output",
        "",
        f"Output is written to the **`{v['output_folder']}`** folder, named:",
        "",
        f"```\n{v['output_pattern']}\n```",
        "",
    ]
    if v["output_files"]:
        lines.append("Files produced:")
        lines.append("")
        for f in v["output_files"]:
            lines.append(f"- **`{f['name']}`** — {f['tooltip']}" if f["tooltip"]
                         else f"- **`{f['name']}`**")
        lines.append("")
    if v["tips"]:
        lines += ["## Tips", "", v["tips"], ""]
    if v["troubleshooting"]:
        lines += ["## Troubleshooting", "", "| If… | Then… |", "|------|-------|"]
        for t in v["troubleshooting"]:
            prob = t["problem"].replace("|", "\\|")
            fix = t["fix"].replace("|", "\\|")
            lines.append(f"| {prob} | {fix} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# HTML rendering (one self-contained, bundleable guide).
# ---------------------------------------------------------------------------

def _h(s: str) -> str:
    return html.escape(s or "")


def render_skill_html(v: dict) -> str:
    badge = "offline · no LLM" if v["offline"] else "needs LLM endpoint"
    badge_cls = "ok" if v["offline"] else "warn"
    parts = [f'<section id="{_h(v["dir"])}" class="skill">']
    parts.append(f'<h2>{_h(v["display_name"])} '
                 f'<span class="badge {badge_cls}">{_h(badge)}</span> '
                 f'<span class="badge">{_h(v["mode"])}</span></h2>')
    parts.append(f'<p class="overview">{_h(v["overview"] or v["description"])}</p>')
    if v["when_to_use"]:
        parts.append(f'<p class="whenuse"><b>When to use it.</b> {_h(v["when_to_use"])}</p>')

    parts.append("<h3>Inputs</h3><ul class=\"inputs\">")
    for inp in v["inputs"]:
        req = "required" if inp["required"] else "optional"
        tip = ""
        if inp["tooltip"] or inp["gotchas"]:
            tip_txt = inp["tooltip"]
            if inp["gotchas"]:
                tip_txt += (" ⚠️ " + inp["gotchas"]) if tip_txt else ("⚠️ " + inp["gotchas"])
            tip = f'<span class="pa-tip" data-tip="{_h(tip_txt)}">ℹ️</span>'
        parts.append(
            f'<li><b>{_h(inp["label"])}</b> <em>({req})</em> {tip}'
            f'<br><span class="fmt">accepts: {_h(inp["formats"])}</span></li>'
        )
    parts.append("</ul>")

    parts.append("<h3>How to run</h3><ol>")
    steps = v["steps"] or ["Provide the input(s) above and click Run."]
    for s in steps:
        parts.append(f"<li>{_h(s)}</li>")
    parts.append("</ol>")

    parts.append("<h3>Output</h3>")
    parts.append(f'<p>Written to <code>{_h(v["output_folder"])}</code>:</p>')
    parts.append(f'<pre>{_h(v["output_pattern"])}</pre>')
    if v["output_files"]:
        parts.append('<ul class="outputs">')
        for f in v["output_files"]:
            tip = (f'<span class="pa-tip" data-tip="{_h(f["tooltip"])}">ℹ️</span>'
                   if f["tooltip"] else "")
            desc = f' — {_h(f["tooltip"])}' if f["tooltip"] else ""
            parts.append(f'<li><code>{_h(f["name"])}</code>{tip}{desc}</li>')
        parts.append("</ul>")
    if v["tips"]:
        parts.append(f'<h3>Tips</h3><p>{_h(v["tips"])}</p>')
    if v["troubleshooting"]:
        parts.append('<h3>Troubleshooting</h3><table class="tbl"><thead><tr>'
                     '<th>If…</th><th>Then…</th></tr></thead><tbody>')
        for t in v["troubleshooting"]:
            parts.append(f'<tr><td>{_h(t["problem"])}</td><td>{_h(t["fix"])}</td></tr>')
        parts.append("</tbody></table>")
    parts.append("</section>")
    return "\n".join(parts)


HTML_CSS = """
:root{--bg:#0f1117;--card:#181b24;--fg:#e6e6e6;--muted:#9aa0ab;--accent:#7aa2f7;
--ok:#3ddc97;--warn:#f7b955;--border:#262a35;}
*{box-sizing:border-box}
body{margin:0;font:15px/1.6 system-ui,Segoe UI,Roboto,sans-serif;background:var(--bg);
color:var(--fg);display:flex}
nav{position:sticky;top:0;align-self:flex-start;width:240px;height:100vh;overflow:auto;
padding:18px 14px;border-right:1px solid var(--border);background:var(--card)}
nav h1{font-size:16px;margin:0 0 12px}
nav input{width:100%;padding:7px 9px;margin-bottom:12px;background:#0f1117;color:var(--fg);
border:1px solid var(--border);border-radius:7px}
nav a{display:block;color:var(--muted);text-decoration:none;padding:4px 6px;border-radius:6px;
font-size:13.5px}
nav a:hover{background:#20242f;color:var(--fg)}
main{flex:1;padding:28px 40px;max-width:900px}
h2{border-bottom:1px solid var(--border);padding-bottom:6px;margin-top:42px}
.skill:first-of-type h2{margin-top:8px}
.badge{font-size:11px;font-weight:600;padding:2px 8px;border-radius:20px;background:#262a35;
color:var(--muted);vertical-align:middle;margin-left:6px}
.badge.ok{background:rgba(61,220,151,.15);color:var(--ok)}
.badge.warn{background:rgba(247,185,85,.15);color:var(--warn)}
.overview{color:#cfd3da}
.whenuse{background:#141822;border-left:3px solid var(--accent);padding:8px 12px;
border-radius:0 7px 7px 0;color:#cfd3da}
.fmt{color:var(--muted);font-size:13px}
table.tbl{border-collapse:collapse;width:100%;margin:8px 0}
table.tbl th,table.tbl td{border:1px solid var(--border);padding:7px 10px;text-align:left;
font-size:13.5px;vertical-align:top}
table.tbl th{background:#141822;color:var(--fg)}
code{background:#11141c;padding:1px 6px;border-radius:5px;color:#cbd5ff}
pre{background:#11141c;padding:12px 14px;border-radius:8px;overflow:auto;border:1px solid var(--border)}
ul.inputs li,ul.outputs li{margin:6px 0}
.pa-tip{cursor:help;position:relative;margin-left:5px}
.pa-tip:hover::after{content:attr(data-tip);position:absolute;left:18px;top:-4px;z-index:9;
width:280px;background:#0b0d13;color:var(--fg);border:1px solid var(--accent);
padding:8px 10px;border-radius:8px;font-size:12.5px;font-weight:400;white-space:normal;
box-shadow:0 6px 22px rgba(0,0,0,.5)}
footer{color:var(--muted);font-size:12px;margin-top:48px;border-top:1px solid var(--border);
padding-top:14px}
"""

HTML_JS = """
const q=document.getElementById('q'),links=[...document.querySelectorAll('nav a')];
q.addEventListener('input',()=>{const t=q.value.toLowerCase();
links.forEach(a=>a.style.display=a.textContent.toLowerCase().includes(t)?'block':'none');});
"""


def render_html(views: list[dict], version_note: str) -> str:
    nav = "\n".join(
        f'<a href="#{_h(v["dir"])}">{_h(v["display_name"])}</a>' for v in views
    )
    body = "\n".join(render_skill_html(v) for v in views)
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>PA Skills Portable — User Guide</title>
{GENERATED_BANNER}
<style>{HTML_CSS}</style></head>
<body>
<nav><h1>PA Skills — Help</h1>
<input id="q" placeholder="Filter skills…" autocomplete="off">
{nav}
</nav>
<main>
<h1>User Guide</h1>
<p class="overview">Every skill writes to the <code>Data/outputs/</code> folder with a
timestamped filename. Hover the ℹ️ icons for input tips and how to read each output.</p>
{body}
<footer>{_h(version_note)}</footer>
</main>
<script>{HTML_JS}</script>
</body></html>
"""


# ---------------------------------------------------------------------------
# Dev reference (UI skills + internal steps).
# ---------------------------------------------------------------------------

def render_dev_reference(views: list[dict], internal: list[dict]) -> str:
    lines = [MD_BANNER, "# Skills Reference (developer)", "",
             "Auto-generated inventory of every skill. UI skills appear as tabs; "
             "internal steps run only inside the GnuCash Import pipeline.", "",
             "## UI skills", "",
             "| Skill | Dir | Mode | LLM | Inputs | Output | Native deps |",
             "|-------|-----|------|-----|--------|--------|-------------|"]
    for v in views:
        ins = "; ".join(f"{i['label']} ({i['formats']})" for i in v["inputs"]) or "—"
        deps = ", ".join(v["native"] + v["external"]) or "—"
        llm = "no" if v["offline"] else "yes"
        lines.append(
            f"| {v['display_name']} | `{v['dir']}` | {v['mode']} | {llm} | "
            f"{ins} | `{v['output_pattern'].split('/')[-1]}` | {deps} |"
        )
    lines += ["", "## Internal pipeline steps", "",
              "Not registered as UI tabs (no `display_name`). Used programmatically "
              "by `skill_gnucash_pipeline`.", "",
              "| Step (dir) | Category | LLM | What it does |",
              "|------------|----------|-----|--------------|"]
    for s in internal:
        lines.append(f"| `{s['dir']}` | {s['category']} | "
                     f"{'yes' if s['llm'] else 'no'} | {s['description']} |")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Driver.
# ---------------------------------------------------------------------------

def build() -> dict[Path, str]:
    skills = registry.discover(refresh=True)
    views = [skill_view(s) for s in skills]
    internal = internal_steps()
    # NB: no generation date here — stamping date.today() made the committed
    # HTML "stale" every day after commit, breaking the docs-freshness check
    # non-deterministically. Keep the note deterministic (counts only).
    version_note = (f"Generated from skill manifests · "
                    f"{len(views)} UI skills, {len(internal)} internal steps.")

    out: dict[Path, str] = {}
    for v in views:
        out[DOCS / "user-guide" / f"{v['dir']}.md"] = render_skill_md(v)
    out[DOCS / "USER-GUIDE.html"] = render_html(views, version_note)
    out[DOCS / "dev" / "skills-reference.md"] = render_dev_reference(views, internal)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if any output is stale (CI mode); write nothing.")
    args = ap.parse_args()

    outputs = build()
    stale = []
    for path, content in outputs.items():
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            print("Stale docs (run scripts/gen_docs.py):")
            for p in stale:
                print(f"  - {p.relative_to(ROOT)}")
            return 1
        print("Docs up to date.")
        return 0

    print(f"Wrote {len(outputs)} file(s):")
    for p in outputs:
        flag = "  (changed)" if p in stale else ""
        print(f"  - {p.relative_to(ROOT)}{flag}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
