"""
tests/skill_itr_workbook/test_parse_foreign.py -- parser for the broker
"consolidated tax report" (Schedule FA / Schedule FSI / Form 67 / Schedule
TR / Dividend / Interest). Fully offline: the only input is the synthetic
fixture generated by fixture_gen_fa.py (tests/skill_itr_workbook/fixtures/
syn_indmoney_tax_report.xlsx), which is faithful in LAYOUT to a real
INDmoney report and entirely invented in CONTENT. No real financial data is
read anywhere in this file.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "src"
SCRIPTS = SRC / "agents" / "skill_itr_workbook" / "scripts"
FIXTURES = Path(__file__).resolve().parent / "fixtures"
FIXTURE_XLSX = FIXTURES / "syn_indmoney_tax_report.xlsx"

for p in (str(SCRIPTS), str(Path(__file__).resolve().parent)):
    if p not in sys.path:
        sys.path.insert(0, p)

import parse_foreign as pf  # noqa: E402


@pytest.fixture(scope="module")
def report() -> pf.ForeignIncomeReport:
    return pf.load_foreign_income_report(FIXTURE_XLSX)


# ---------------------------------------------------------------------------
# Shared value parser
# ---------------------------------------------------------------------------

def test_parse_numeric_cell_real_number():
    assert pf.parse_numeric_cell(1234.5) == (1234.5, None)
    assert pf.parse_numeric_cell("1,234.50") == (1234.5, None)
    assert pf.parse_numeric_cell(0) == (0.0, None)


@pytest.mark.parametrize("glyph", ["-", "#", "*"])
def test_parse_numeric_cell_placeholder_glyphs_never_become_zero(glyph):
    value, flag = pf.parse_numeric_cell(glyph)
    assert value is None
    assert flag == f"placeholder:{glyph}"


def test_parse_numeric_cell_prose_is_flagged_not_coerced():
    value, flag = pf.parse_numeric_cell(
        "To be filled by user basis Individual slab rates"
    )
    assert value is None
    assert flag.startswith("prose:")


def test_parse_numeric_cell_empty():
    assert pf.parse_numeric_cell(None) == (None, "empty")
    assert pf.parse_numeric_cell("   ") == (None, "empty")


# ---------------------------------------------------------------------------
# Embedded-newline country cells -- two different real-world formats
# ---------------------------------------------------------------------------

def test_split_country_cell_no_leading_space():
    assert pf.split_country_cell("002\nUnited States of America") == (
        "002", "United States of America",
    )


def test_split_country_cell_with_leading_space_after_newline():
    # Schedule TR's fixture cell has a leading space after the \n, unlike
    # Schedule FSI's -- both are real layout variance and both must resolve
    # to the same clean country name.
    assert pf.split_country_cell("002\n United States of America") == (
        "002", "United States of America",
    )


def test_split_country_cell_empty():
    assert pf.split_country_cell(None) == (None, None)


# ---------------------------------------------------------------------------
# Schedule FA -- A2 (custodial accounts)
# ---------------------------------------------------------------------------

def test_schedule_fa_a2_custodial_account_parsed(report):
    accounts = report.schedule_fa.custodial_accounts
    assert len(accounts) == 1
    acct = accounts[0]
    assert acct.country == "United States of America"
    assert acct.country_code == "002"
    assert acct.institution == "SynBroker LLC"
    assert acct.account_number == "SYN000001"
    assert acct.peak_balance == 5000
    assert acct.closing_balance == 800
    assert acct.gross_amount_nature == "Interest"
    # The two-row merged-parent header ("Gross amount paid/credited..." over
    # "Nature of Amount"/"Amount") must resolve to the AMOUNT sub-column,
    # not fall back onto the nature-of-amount text.
    assert acct.gross_amount == 9
    assert acct.flags == {}


# ---------------------------------------------------------------------------
# Schedule FA -- A3 (equity/debt interest), one row per LOT
# ---------------------------------------------------------------------------

def test_schedule_fa_a3_never_dedupes_by_entity_name(report):
    lots = report.schedule_fa.equity_lots
    alpha_lots = [l for l in lots if l.entity == "SynCo Alpha Ltd (ADR)"]
    # The fixture deliberately repeats the same entity, same acquisition
    # date, same address across two rows with DIFFERENT financial figures.
    # A parser that dedupes by entity name would collapse this to one row
    # and silently drop money.
    assert len(alpha_lots) == 2, (
        "Schedule FA A3 must keep one row per acquisition LOT -- a parser "
        "that dedupes by entity name loses a real lot's figures."
    )
    initial_values = sorted(l.initial_value for l in alpha_lots)
    assert initial_values == [5000, 100000]
    gross_values = sorted(l.gross_amount_credited for l in alpha_lots)
    assert gross_values == [75, 1500]


def test_schedule_fa_a3_total_lot_count(report):
    # 2 lots for SynCo Alpha Ltd (ADR) + 1 for SynCo Beta Inc.
    assert len(report.schedule_fa.equity_lots) == 3


def test_schedule_fa_a3_beta_lot_fields(report):
    beta = [l for l in report.schedule_fa.equity_lots if l.entity == "SynCo Beta Inc."]
    assert len(beta) == 1
    lot = beta[0]
    assert lot.date_acquired == "2024-12-02"
    assert lot.initial_value == 110000
    assert lot.peak_value == 140000
    assert lot.closing_value == 130000
    assert lot.gross_amount_credited == 2500
    assert lot.country == "United States of America"
    assert lot.broker == "SynBroker LLC"


# ---------------------------------------------------------------------------
# Schedule FSI -- vertically-merged country/TIN block, (a)..(f) letter row,
# four fixed heads of income
# ---------------------------------------------------------------------------

def test_schedule_fsi_four_heads_of_income(report):
    heads = [r.head_of_income for r in report.schedule_fsi.rows]
    assert heads == ["Salary", "House Property", "Capital Gains", "Other Sources"]


def test_schedule_fsi_placeholder_heads_are_none_not_zero(report):
    salary = report.schedule_fsi.rows[0]
    assert salary.income is None
    assert salary.flags.get("income") == "placeholder:-"


def test_schedule_fsi_capital_gains_real_zero_is_not_a_placeholder(report):
    # The fixture writes a literal 0 (not "-") for Capital Gains income --
    # that IS a real, asserted zero and must come through as 0.0, not None.
    cg = report.schedule_fsi.rows[2]
    assert cg.income == 0.0
    assert "income" not in cg.flags


def test_schedule_fsi_other_sources_income(report):
    other = report.schedule_fsi.rows[3]
    assert other.income == 4203
    assert other.tax_paid_outside == 735
    assert other.tax_payable_india is None  # placeholder "*" in the fixture
    assert other.flags.get("tax_payable_india") == "placeholder:*"
    assert other.tax_relief is None  # prose "Lower of (c) or (d)" in the fixture
    assert other.flags.get("tax_relief") == "prose:Lower of (c) or (d)"


def test_schedule_fsi_country_tin_block_applies_to_every_head_row(report):
    # The country/TIN cells are merged vertically across all four
    # head-of-income rows in the source; every row must carry them.
    for row in report.schedule_fsi.rows:
        assert row.country == "United States of America"
        assert row.country_code == "002"
        assert row.tin == "Your TIN in USA (if available) or your Passport Number"


def test_schedule_fsi_other_sources_ties_to_dividend_plus_interest(report):
    # Deliberate TIE (Schedule FSI's "Other Sources" income is a financial-
    # year figure, same basis as Dividend/Interest): worth asserting.
    fsi_other = report.schedule_fsi.other_sources_income
    fy_total = report.dividend.total + report.interest.total
    assert fsi_other == fy_total


# ---------------------------------------------------------------------------
# Form 67 -- merged parent header + a sub-header whose column-9..11 labels
# do NOT semantically match the parent header's text at those columns
# ---------------------------------------------------------------------------

def test_form_67_two_rows(report):
    assert len(report.form_67.rows) == 2
    sources = [r.source_of_income for r in report.form_67.rows]
    assert sources == ["Dividend", "Interest"]


def test_form_67_dividend_row_amounts(report):
    row = report.form_67.rows[0]
    assert row.country == "USA"
    assert row.income == 4200
    assert row.tax_paid_amount == 732
    assert row.tax_paid_rate == "17.43%"


def test_form_67_interest_row_tax_paid_is_placeholder(report):
    row = report.form_67.rows[1]
    assert row.income == 3
    assert row.tax_paid_amount is None
    assert row.flags.get("tax_paid_amount") == "placeholder:-"


def test_form_67_other_cells_preserved_verbatim_not_misassigned(report):
    # Header row's column 9 says "Credit claimed under section 90/90A" but
    # the sub-header row's column 9 says "Article No. of Double Taxation
    # Avoidance Agreements" -- these do not agree. Rather than guess which
    # is authoritative, everything not in the named fields must survive
    # verbatim, keyed by the header-row label, so no content is lost.
    row = report.form_67.rows[0]
    assert any("115JB/JC" in k for k in row.other_cells)
    assert any("section 91" in k for k in row.other_cells)


# ---------------------------------------------------------------------------
# Schedule TR
# ---------------------------------------------------------------------------

def test_schedule_tr_row(report):
    assert len(report.schedule_tr.rows) == 1
    row = report.schedule_tr.rows[0]
    assert row.country_code == "002"
    assert row.country == "United States of America"  # leading-space format
    assert row.total_taxes_paid_outside == 735
    assert row.relief_claimed_under_section == 90
    assert row.non_dtaa_relief == 0
    assert row.refunded_or_credited == "No"


# ---------------------------------------------------------------------------
# Dividend
# ---------------------------------------------------------------------------

def test_dividend_total_and_payments(report):
    assert report.dividend.total == 4200
    assert len(report.dividend.payments) == 4
    names = {p.company for p in report.dividend.payments}
    assert names == {
        "SynCo Beta Inc. Common Stock",
        "SynCo Alpha Ltd American Depositary Shares",
    }


def test_dividend_quarterly_bucket_sums_to_total(report):
    # The real report has a completely blank spacer row between the
    # "Quaterly Break - Up" title and the "Particulars" label row -- the
    # fixture now matches that layout. This is the regression test for the
    # bug where an adjacent-row assumption landed on the blank spacer and
    # silently produced zero buckets.
    buckets = report.dividend.quarterly
    income_buckets = [b for b in buckets if b.series == "Dividend Income"]
    assert len(income_buckets) == 5
    total = sum(b.amount for b in income_buckets if b.amount is not None)
    assert total == report.dividend.total
    # First quarter is a literal "-" placeholder, not a real zero.
    first = income_buckets[0]
    assert first.amount is None
    assert first.flag == "placeholder:-"


def test_dividend_quarterly_both_series_captured(report):
    # Both data rows under the label row are series, not just the first --
    # "Dividend u/s 2(22)(f)" is buyback dividend, taxed differently.
    buckets = report.dividend.quarterly
    series_names = {b.series for b in buckets}
    assert series_names == {"Dividend Income", "Dividend u/s 2(22)(f)"}
    buyback_buckets = [b for b in buckets if b.series == "Dividend u/s 2(22)(f)"]
    assert len(buyback_buckets) == 5
    # Every buyback-dividend cell in the fixture is a "-" placeholder.
    for b in buyback_buckets:
        assert b.amount is None
        assert b.flag == "placeholder:-"


def test_dividend_quarterly_title_found_but_no_label_row_warns(tmp_path):
    # Degenerate case built in-memory: a Quarterly Break-Up title row with no
    # label row beneath it at all (e.g. the title sits right above an
    # unrelated section). The parser must not silently return an empty list
    # -- it must warn loudly that the block was found but yielded nothing.
    import openpyxl

    wb = openpyxl.Workbook()
    for name in pf.REQUIRED_SHEETS:
        if name not in wb.sheetnames:
            wb.create_sheet(name)
    if "Sheet" in wb.sheetnames:
        del wb["Sheet"]

    ws = wb["Dividend"]
    ws.append(["Financial Year:", "FY2025-26"])
    ws.append(["Particulars", "Amount (₹)", "ITR Section"])
    ws.append(["US Stocks", 100, "Schedule OS U/s Dividend"])
    ws.append(["Total", 100])
    ws.append([])
    ws.append(["Quaterly Break - Up"])
    for _ in range(6):
        ws.append([])   # nothing resembling a label row anywhere below
    ws.append(["Disclaimer: synthetic test data only."])

    for name in pf.REQUIRED_SHEETS:
        if name != "Dividend":
            wb[name].append(["placeholder"])

    xlsx_path = tmp_path / "degenerate_quarterly.xlsx"
    wb.save(xlsx_path)

    result = pf.load_foreign_income_report(xlsx_path)
    assert result.dividend.quarterly == []
    assert any(
        "Quarterly Break-Up" in w and "label row" in w for w in result.warnings
    ), result.warnings


# ---------------------------------------------------------------------------
# Interest -- total lives at a row that precedes the sheet's own title row,
# and data rows never populate a broker despite the header implying one
# ---------------------------------------------------------------------------

def test_interest_total_found_ahead_of_title_row(report):
    assert report.interest.total == 3


def test_interest_receipts_have_no_broker(report):
    assert len(report.interest.receipts) == 3
    for r in report.interest.receipts:
        assert r.broker is None
        assert r.amount_inr == 1


# ---------------------------------------------------------------------------
# Deliberate non-tie: Schedule FA is a CALENDAR year, Dividend/Interest are
# a FINANCIAL year -- these are NOT expected to match, and "fixing" this
# would be wrong.
# ---------------------------------------------------------------------------

def test_schedule_fa_gross_amounts_do_not_tie_to_fy_dividend_interest(report):
    fa_gross_total = sum(
        l.gross_amount_credited for l in report.schedule_fa.equity_lots
        if l.gross_amount_credited is not None
    )
    fy_total = report.dividend.total + report.interest.total
    assert fa_gross_total != fy_total, (
        "Schedule FA reports a CALENDAR year and Dividend/Interest report a "
        "FINANCIAL year -- these figures are allowed, and expected, to "
        "differ. If this ever starts passing as equal, the fixture (or the "
        "parser) changed in a way that needs re-checking, not 'fixing' this "
        "assertion away."
    )


# ---------------------------------------------------------------------------
# Vendor-stated limitations -- matched by stable substring, absence flagged
# rather than the parser failing
# ---------------------------------------------------------------------------

def test_vendor_limits_present_ones_detected(report):
    present = {v.key for v in report.vendor_limits if v.present}
    assert "indglobal_dividends_excluded" in present
    assert "delisted_stock_peak_closing_omitted" in present
    assert "corporate_actions_stock_splits_only" in present
    assert "sbi_tt_buy_rate" in present
    assert "us_timezone" in present


def test_vendor_limits_absent_one_is_flagged_not_silently_dropped(report):
    # The fixture's disclaimer list deliberately omits any note about US tax
    # withheld on INDglobal holdings not being captured -- this must show up
    # as an explicit "expected but absent" signal, not vanish.
    limits = {v.key: v.present for v in report.vendor_limits}
    assert limits["indglobal_us_tax_not_captured"] is False
    assert any(
        "US tax withheld on INDglobal" in w for w in report.warnings
    )


# ---------------------------------------------------------------------------
# Missing-sheet / structural failure handling
# ---------------------------------------------------------------------------

def test_missing_required_sheet_raises(tmp_path):
    from openpyxl import Workbook

    wb = Workbook()
    wb.active.title = "Not A Real Sheet"
    bogus = tmp_path / "bogus.xlsx"
    wb.save(bogus)
    with pytest.raises(pf.ForeignReportError):
        pf.load_foreign_income_report(bogus)


def test_missing_header_in_present_sheet_does_not_raise(tmp_path):
    # A present-but-empty required sheet must not raise -- only degrade
    # that one schedule to parsed=False with a warning, so other sheets in
    # the same report still get read.
    from openpyxl import Workbook

    wb = Workbook()
    wb.active.title = pf.REQUIRED_SHEETS[0]
    for name in pf.REQUIRED_SHEETS[1:]:
        wb.create_sheet(name)
    empty = tmp_path / "empty_sheets.xlsx"
    wb.save(empty)
    rep = pf.load_foreign_income_report(empty)
    assert rep.schedule_fa.parsed is False
    assert rep.schedule_fsi.parsed is False
    assert len(rep.warnings) > 0


# ---------------------------------------------------------------------------
# Sheets found by name, not position
# ---------------------------------------------------------------------------

def test_report_ignores_unrelated_sheets_by_name(report):
    # The real fixture workbook also has LTCG/STCG/F&O/Intraday/Bonds & SGB
    # sheets that this parser must never touch; if sheet lookup were
    # positional instead of by-name, load_foreign_income_report would have
    # blown up or read garbage well before reaching this assertion.
    assert report.schedule_fa.custodial_accounts
    assert report.schedule_fsi.rows
